### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by davidmoshal** [webix-hub/webix-firebase#1]
Any news on this.

Ideally it would include making Webix 'reactive', something like how GluJs works with Extjs, a similar declarative javascript UI framework.

http://glujs.com/

That is, in order to work well with Firebase, Webix probably needs to support an MVVM pattern.

David

**Comment by mkozhukh** [comment]
Hi, 

I have created a working prototype, just need to document how to use it 

It works quite nicely, you can link any data component to the FireBase collection after that it will automatically save and update data for all clients. There is no any heavy framework though, just a data integration layer.

**Comment by davidmoshal** [comment]
I am VERY interested is seeing this !

Note, in addition to wiring "collections data" to Firebase, wiring arbitrary UI properties to Firebase is very useful.

**Comment by mkozhukh** [comment]
Version 0.1 is ready

**Comment by davidmoshal** [comment]
Nice! 
Note: your Kanban demo isn't syncing task ordering in columns

**Comment by mkozhukh** [comment]
Yep, the adapter doesn't support data ordering yet  
It will be solved in the next update
