### ISSUE TITLE
Using proxy in angular apps

### ISSUE THREAD

**Issue by kroupa1985** [webix-hub/webix-firebase#2]
Hi,

I am using this proxy in angularJs application controller.

The problem is everytime i use it i get to much recursion error.

Is there any way to bypass this ?

**Comment by kroupa1985** [comment]
I've managed to resolve the isshue before, now iam getting this error:

Error: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com 

My logic looks like this:
webix.firebase = new Firebase('https://itbs-beauty-booking.firebaseio.com');

The isshue is only present in angularJs application. In an simple page example widget shows data with this url settings.

Can anybody help please.

**Comment by mkozhukh** [comment]
I'm closing this issue as part of repo cleaning. 
Please reopen the issue if it is still actual
