### ISSUE TITLE
Firebase exception

### ISSUE THREAD

**Issue by kroupa1985** [webix-hub/webix-firebase#3]
I am using webix form in window to update a record in firebase.

I am also using a datatable to display all records in a collection. When a update happens the following exception occurs:

FIREBASE WARNING: Exception was thrown by user callback. webix.DataStore.prototype.getItem@https://cdn.webix.com/edge/webix.js:375:23
webix.DataStore.prototype.updateItem@https://cdn.webix.com/edge/webix.js:375:75
webix.DataStore.prototype.Ef/<@https://cdn.webix.com/edge/webix.js:392:174
webix.proxy.firebase.load/</<@http://www.caliopa.com/libs/webix-firebase-master/codebase/webix-firebase.js:46:5
webix.DataProcessor<.ignore@https://cdn.webix.com/edge/webix.js:1129:49
webix.proxy.firebase.load/<@http://www.caliopa.com/libs/webix-firebase-master/codebase/webix-firebase.js:45:4
g.Vb/<@https://cdn.firebase.com/js/client/2.3.1/firebase.js:48:373
Db@https://cdn.firebase.com/js/client/2.3.1/firebase.js:43:165
zb@https://cdn.firebase.com/js/client/2.3.1/firebase.js:22:216
Ab@https://cdn.firebase.com/js/client/2.3.1/firebase.js:21:1260
g.update@https://cdn.firebase.com/js/client/2.3.1/firebase.js:210:471
U.prototype.update@https://cdn.firebase.com/js/client/2.3.1/firebase.js:251:431
formWindow.head.cols<.click@http://www.caliopa.com/controllers/panogeController.js:133:12
@https://cdn.webix.com/edge/webix.js:271:69
webix.EventSystem.callEvent@https://cdn.webix.com/edge/webix.js:21:331
@https://cdn.webix.com/edge/webix.js:38:294

In a button click handler i have a following code:
var sifrant = { title:"test" }

ref.update(sifrant, function(error){
  if (error) {
    webix.message("error message");
  }
  else {
    webix.message("succes message");
  }
});

There is no error triggered in the callback.

**Comment by kroupa1985** [comment]
Application is hosted on http://caliopa.ultimatefreehost.id. You can see it i action there.

**Comment by kroupa1985** [comment]
This exception occours even if i delete a record in datatable

**Comment by mkozhukh** [comment]
I'm closing this issue as part of repo cleaning. 
Please reopen the issue if it is still actual
