### ISSUE TITLE
Double Data Loading

### ISSUE THREAD

**Issue by ghost** [webix-hub/webix-firebase#4]
Data is loading twice into my table from Firebase. It looks like rows are being added from both the ref.once("value") and ref.on("child_added"). I'm guessing this is happening because I loaded the firebase ref at an earlier point in my app, so the functions were probably getting  called synchronously.

I was able to fix the problem by wrapping the webix.ajax.$callback in a setTimeout

``` javascript
            setTimeout(function(){
                webix.ajax.$callback(view, callback, "", result, -1);
            }, 1)
```

**Comment by Rasalexman** [comment]
I have the same issue on function $$("mydatatable").load(ref); from firebase .
Data loading twice after i change my ref back to datatable.

var db = firebase.database();
var proxy = webix.proxy("firebase", db.ref(id));
$$("dtable").load(proxy);
          

can anybody help me?

**Comment by mkozhukh** [comment]
There was an issue with processing both value and child-add events.
Must be fixed now
