### ISSUE TITLE
Update after the Firebase re-release

### ISSUE THREAD

**Issue by dandv** [webix-hub/webix-firebase#5]
Now that Google released the full suite of Firebase MBAAS APIs at I/O 2016, it would be great to see some updates to this adapter, starting with the CDN URL in the README.

The samples are broken now, because [the 3.x API no longer uses the `Firebase` object](https://firebase.google.com/support/guides/firebase-web#get_a_database_reference_numbered).

**Comment by mkozhukh** [comment]
Adapter added to work with 3.x API
