### ISSUE TITLE
Clipboard paste do not save into Firebase DB

### ISSUE THREAD

**Issue by pavelbinar** [webix-hub/webix-firebase#9]
Using following datatable settings: 
```
{
    select: 'cell',
    multiselect: true,
    editable: true,
    clipboard: 'repeat',
    editaction: 'dblclick',
}
```

The value is placed into the call but not saved into the Firebase so it disappears after browser reload.

**Comment by mkozhukh** [comment]
Any action which triggers data saving will start sync with  firebase.
Unfortunately, datatable doesn't trigger saving events for paste operations, it must be fixed on widget's level to work here and for all other data saving protocols.
